language: php
php:
  - 5.6
  - 7

sudo: false

install: travis_retry composer install --no-interaction --prefer-dist

before_script:
    - sleep 10

script: vendor/bin/phpunit --verbose --coverage-clover=coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)